# Generated by Django 2.2.6 on 2021-12-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211230_0112'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='NoDuplicateRecipeInShoppingList',
        ),
    ]
