# Generated by Django 2.2.6 on 2021-12-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211230_0126'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='NoDuplicateRecipeInShoppingList'),
        ),
    ]
